streeboutique/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.header_footer, name='header_footer'),
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('search/', views.search, name='search'),
    path('product/<str:id>', views.product, name='product'),
    path('contact/', views.contact, name='contact'),
    path('register/', views.register, name ='register'),
    path('login/', views.user_login, name ='login'),
    path('logout/', views.user_logout, name='logout'),
    path('term_condition/', views.term_condition, name='term_condition'),
    path('private_policy/', views.private_policy, name='private_policy'),
    path('faq/', views.faq, name='faq'),
    # path('order_tracking/', views.order_tracking, name='order_tracking'),
    path('about_us/', views.about_us, name='about_us'),
     path('service/', views.service, name='service'),


    #account
    path('order_page/', views.order_page, name='order_page'),
    path('order/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),

    #login

    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('varify/', views.varify, name='varify'),
    path('change_pwd/', views.change_pwd, name='change_pwd'),

    #wishlit
    path('wishlist/', views.view_wishlist, name='wishlist'),
    path('wishlist/add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    
    #cart
    path('cart/', views.cart_details, name='cart'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart_clear/', views.cart_clear, name='cart_clear'),
    path('place_order/', views.place_order, name='place_order'), 
    path('invoice/<int:order_id>/', views.invoice, name='invoice'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User



# Create your models here.


class Categories(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name
    
    code = models.CharField(max_length=50)
    def __str__(self):
        return self.code


class Filter_price(models.Model):
    filter_price = (
        ('200 TO 500', '200 TO 500'),
        ('500 TO 1000', '500 TO 1000'),
        ('1000 TO 5000', '1000 TO 5000'),
        ('5000 TO 10000', '5000 TO 10000'),
        ('10000 TO 20000', '10000 TO 20000'),
        ('20000 TO 50000', '20000 TO 50000'),
    )
    
    price = models.CharField(choices=filter_price, max_length=60)
    def __str__(self):
        return self.price

class Product(models.Model):
    condition_choice = (('New', 'New') , ('Sale', 'Sale'), ('50% Off', '50% Off'), ('75% Off', '75% Off'))
    stock = (('In Stock', 'In Stock') , ('Out Of Stock', 'Out Of Stock'))
    status = (('Publish', 'Publish') , ('Draft', 'Draft'))

    u_id = models.CharField(unique=True, max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to='product_images/image')
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    condition = models.CharField(choices=condition_choice, max_length=100)
    discount = models.IntegerField(null=True, default=0)
    information = RichTextField(null=True)
    description = RichTextField(null=True)
    stock = models.CharField(choices=stock,max_length=200)
    # totalStock = models.IntegerField(default=0)
    status = models.CharField(choices=status,max_length=200)
    avl_date = models.DateTimeField(default=timezone.now)

    categories = models.ForeignKey(Categories,on_delete = models.CASCADE)
    brand = models.ForeignKey(Brand,on_delete = models.CASCADE)
    color = models.ForeignKey(Color,on_delete = models.CASCADE)
    filter_price = models.ForeignKey(Filter_price,on_delete = models.CASCADE)

    def __str__(self):
        return self.name

# def save(self,args, **kwargs):
#     if self.id is None and self.avl_date and self.gen_id:
#         self.id = self.avl_date.strftime('75%Y%m%d24') + str(self.gen_id)
#     return Super().save(*args,**kwargs)

def save(self, *args, **kwargs):
        if self.u_id is None and self.avl_date:
            # Assuming self.gen_id is defined elsewhere; otherwise, adjust as needed
            self.u_id = self.avl_date.strftime('%Y%m%d%H%M%S') + str(self.gen_id)
        super(Product, self).save(*args, **kwargs) 


class Images(models.Model): 
    image = models.ImageField(upload_to='product_images/image')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

class Tag(models.Model):
    name = models.CharField(max_length=200)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Size(models.Model):
    size = models.CharField(max_length=10)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.size
    
class Product_Color(models.Model):
    color = models.CharField(max_length=30)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.color
    
class Contact(models.Model):
    name = models.CharField(max_length=60)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=200)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email
    
class Order(models.Model):

    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('canceled', 'Canceled'),
    )

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    f_name = models.CharField(max_length=100)
    l_name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    address = models.TextField()
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    post_code = models.IntegerField()
    phone = models.IntegerField()
    email = models.EmailField(max_length=100)
    additional_info = models.TextField(blank=True, null=True)
    amount = models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True)


    def __str__(self):
        # return self.User.user
        return f"Order #{self.id}"
    
    def cancel(self):
        if self.status == 'pending' or self.status == 'processing':
            self.status = 'canceled'
            self.save()
    
    
class Order_item(models.Model): 
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=200)
    image = models.ImageField(upload_to='product_images/order_img')
    quantity = models.CharField(max_length=20)
    price = models.CharField(max_length=50)
    total = models.CharField(max_length=1000)

    def __str__(self):
        return f"Order item {self.id}"
    
class Wishlist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='wishlist')
    products = models.ManyToManyField(Product, related_name='wishlists', blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Wishlist of {self.user.username}'
    
class Cart1(models.Model):
    item = models.ForeignKey(Product, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, default=None)
    clr = models.ForeignKey(Product_Color, on_delete=models.CASCADE, default=None)
    image = models.CharField(max_length=100, default=None)
    name = models.CharField(max_length=100, default=None)
    price = models.IntegerField(default=None)
    quantity = models.IntegerField(default=None)
    sbt = models.IntegerField(default=None)
    

shop/views.py
from django.shortcuts import render

# Create your views here.

templates/main/about_us.html
{% extends "main/header_footer.html" %}

{% block content %}

{% load static %}
<!-- breadcrumb-area start -->
<div class="breadcrumb-area" data-bg-image="{% static 'assets/images/shopping.gif' %}">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-12 text-center">
                <h2 class="breadcrumb-title">About Us</h2>
                <!-- breadcrumb-list start -->
                <ul class="breadcrumb-list">
                    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                    <li class="breadcrumb-item active">About Us</li>
                </ul>
                <!-- breadcrumb-list end -->
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb-area end -->
<!-- About section Start -->
<div class="about-area pt-100px">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="about-wrapper text-center">
                    <div class="about-contant">
                        <h2 class="title">
                            <span>Smart Fashion </span>
                            With Stree Boutique
                        </h2>
                        <p style="text-align:left;">
                            Welcome to Streeboutique, where style meets attitude. Nestled in the heart of the city, Streeboutique caters exclusively to the modern, confident woman who embraces her individuality.
                            <br>
                            From sophisticated office attire to glamorous evening wear and casual weekend staples, Streeboutique offers a diverse range of fashion choices that cater to every aspect of a woman's life. 
                            <br>
                            At Streeboutique, we believe that fashion is more than just clothing—it's a form of expression. That's why our collections are carefully curated to reflect the latest trends while maintaining a timeless appeal.
                            <br>
                            Step into Streeboutique and discover a world where fashion meets passion, where every piece tells a story, and where your style journey begins.
                        <p>
                        </div>
                        <div class="promo-video" style="margin-top: 2.5%;">
                            <div style="position: relative;">
                                <img src="{% static 'assets/images/about.jpg' %}" alt="" style="height: 30%; width: 79%;">
                        
                                <!-- Absolute positioning for text overlay -->
                                <h3 style="position: absolute; top: 10px; left: 80px; color: red; padding: 5px;margin-left:35%;margin-top:5%;">
                                    streeboutique
                                </h3>
                        
                                <!-- Play button overlay -->
                                <a href="{% static 'assets/images/slide1.gif' %}" class="venobox overlay-box" data-vbtype="gif"
                                    style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);border-radius:50%" >
                                    <span><img src="{% static 'assets/images/about.jpg' %}" alt="" style="border:2px solid black;height: 100%; width: 100%;"><i class="ripple"></i></span>
                                </a>
                            </div>
                        </div>
                        
                        
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About section End -->
<!-- Team Area Start -->
<div class="team-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title text-center">
                    <h2 class="title line-height-1">Team Member</h2>
                    <p> We are student of MCA semster-2 of NJSMTI, Chanduvav</p>
                </div>
            </div>
        </div>
        <div class="row mb-n-30px">
            <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 mb-lm-30px mb-lg-30px mb-md-30px">
                <!-- Single Team -->
                <div class="team-wrapper ">
                    <div class="team-image overflow-hidden">
                        <img src="{% static 'assets/images/selja.jpg' %}" alt="">
                    </div>
                    <div class="team-inner">
                        <div class="team-content">
                            <h6 class="title">Selja Chauhan</h6>
                            <span class="sub-title">Team Member</span>
                        </div>
                    </div>
                </div>
                <!-- Single Team -->
            </div>
            <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 mb-lm-30px mb-lg-30px mb-md-30px">
                <!-- Single Team -->
                <div class="team-wrapper">
                    <div class="team-image overflow-hidden">
                        <img src="{% static 'assets/images/logo/header.png' %}" alt="" style="margin-top:20%;margin-left:10%;eight:300px;width:300px">
                        
                    </div>
                    
                </div>
                <!-- Single Team -->
            </div>
            <div class="col-xl-4 col-lg-4 col-sm-6 col-md-6 mb-lm-30px ">
                <!-- Single Team -->
                <div class="team-wrapper">
                    <div class="team-image overflow-hidden">
                        <img src="{% static 'assets/images/kinjal.jpg' %}" alt="">
                        
                    </div>
                    <div class="team-inner">
                        <div class="team-content">
                            <h6 class="title">Kinjal Kansara</h6>
                            <span class="sub-title">Team Member</span>
                        </div>
                    </div>
                </div>
                <!-- Single Team -->
            </div>
        </div>
    </div>
</div>
<!-- Team Area End -->
<!-- Feature Area Srart -->
<div class="feature-area pt-100px pb-100px">
    <div class="container">
        <div class="feature-wrapper">
            <div class="single-feture-col mb-md-30px mb-lm-30px">
                <!-- single item -->
                <div class="single-feature" >
                    <div class="feature-icon" style="background:#cacfd2">
                        <img src="{%static 'assets/images/24-hours-day-night.png'%} " alt="" height=50 width=50>
                    </div>
                    <div class="feature-content">
                        <h4 class="title">24/7 Hour services</h4>
                        
                    </div>
                </div>
            </div>
            <!-- single item -->
            <div class="single-feture-col mb-md-30px mb-lm-30px">
                <div class="single-feature">
                    <div class="feature-icon" style="background:#cacfd2">
                        <img src="{%static 'assets/images/cod.png'%} " alt="" height=50 width=50>
                    </div>
                    <div class="feature-content">
                        <h4 class="title">Case On Delivery on Each Item</h4>
                        
                    </div>
                </div>
            </div>
            <!-- single item -->
            <div class="single-feture-col">
                <div class="single-feature">
                    <div class="feature-icon" style="background:#cacfd2">
                        <img src="{%static 'assets/images/cancel.png'%} " alt="" height=50 width=50>
                    </div>
                    <div class="feature-content">
                        <h4 class="title">Easy to Order Cancel</h4>
                        
                    </div>
                </div>
                <!-- single item -->
            </div>
        </div>
    </div>
</div>
<!-- Feature Area End -->

        


{% endblock %}

templates/main/order_tracking.html
{% extends "main/header_footer.html" %}

{% block content %}

        <!-- breadcrumb-area start -->
        <div class="breadcrumb-area">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-12 text-center">
                        <h2 class="breadcrumb-title">Order Tracking</h2>
                        <!-- breadcrumb-list start -->
                        <ul class="breadcrumb-list">
                            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                            <li class="breadcrumb-item active">Order Tracking</li>
                        </ul>
                        <!-- breadcrumb-list end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb-area end -->
        <!--order-tracking area start-->
        <div class="pt-100px pb-100px">
            <div class="container">
                <div class="order-tracking">
                    <p>To track your order please enter your Order ID in the box below and press the "Track" button. This was given to you on your receipt and in the confirmation email you should have received.</p>
                    <form action="{% url 'order_tracking' %}" method="post">
                        {% csrf_token %}
                        <div class="row mb-n-30px">
                            <div class="col-12 mb-30px">
                                <label for="billingEmail">Billing email</label>
                                <input id="billingEmail" type="text" placeholder="Email you used during checkout.">
                            </div>
                            <div class="col-12 text-center mb-30px">
                                <button class="btn btn-dark btn-outline-hover-dark">Track</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!--order-tracking Policy area end-->

{% endblock %}

templates/main/product.html
{% extends "main/header_footer.html" %}


{% block content %}

<style>

    .btn{
        color: #002D62;
        background: white;
        border: 2px solid #002D62;
        width: 150%;
        margin-top:3%;
    }

    .btn:hover{
        background:#002D62;
        color: white;
    }

</style>

<!-- Product Details Area Start -->


<div class="product-details-area pt-100px pb-100px">
    
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-12 col-xs-12 mb-lm-30px mb-md-30px mb-sm-30px">
                <!-- Swiper -->
                <div class="swiper-container zoom-top">
                    <div class="swiper-wrapper">
                        {% for i in prod.images_set.all %}
                        <div class="swiper-slide">
                            <img class="img-responsive m-auto" src="/{{i.image}}" alt="" height=500>
                            <a class="venobox full-preview" data-gall="myGallery" href="/{{i.image}}">
                                <i class="fa fa-arrows-alt" aria-hidden="true"></i>
                                <img class="img-responsive m-auto" src="/{{i.image}}" alt="">
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="swiper-container mt-20px zoom-thumbs slider-nav-style-1 small-nav">
                    <div class="swiper-wrapper">
                        {% for i in prod.images_set.all %}
                        <div class="swiper-slide">
                            <img class="img-responsive m-auto" src="/{{i.image}}" alt="">
                            
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Add Arrows -->
                    <div class="swiper-buttons">
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-sm-12 col-xs-12" data-aos="fade-up" data-aos-delay="200">
                <div class="product-details-content quickview-content ml-25px">
                    <h2>{{prod.name}}</h2>
                    <div class="pricing-meta">
                        <ul class="d-flex">
                            <li class="new-price">Rs.{{prod.price}}/-</li>
                        </ul>
                    </div>
                    
                    <p class="mt-30px">{{prod.description | truncatewords:40 | safe}}</p>
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <span>SKU:</span>
                        <ul class="d-flex">
                            <li>
                                <a href="#">{{prod.u_id}}</a>
                            </li>
                        </ul>
                    </div>
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <span>Categories: </span>
                        <ul class="d-flex">
                            <li>
                                <a href="#">{{prod.categories}}</a>
                            </li>
                            
                        </ul>
                    </div>
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <span>Tags: </span>
                        
                        <ul class="d-flex">
                            <li>
                                {% for i in prod.tag_set.all %}
                                <a href="#">{{i.name}}, </a>
                                {% endfor %}
                            </li>
                            
                        </ul> 
                    </div>
                    
                   <form method="post" action="{% url 'cart_add' id=prod.id %}">
                    {% csrf_token %}
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <ul class="d-flex">
                            {% if prod.size_set.all %}
                                <li id="size1">
                                    <span>Size : </span>
                                    <select name="size">
                                        <option disabled selected>Select Size</option>
                                        {% for size in prod.size_set.all %}
                                        {% if size.id == 5 %}
                                        <script>document.getElementById('size1').hidden = true; </script>
                                            {% endif %}
                                            <option value="{{ size.id }}">{{ size.size }}</option>
                                        {% endfor %}
                                    </select> 
                                </li>
                            {% endif %}
                        </ul> 
                    </div>
                    
                    
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <ul class="d-flex">
                            {% if prod.size_set.all %}
                                <li id="color">
                                    <span>Color : </span>
                                    <select name="product_color">
                                        <option disabled selected>Select Color</option>
                                        {% for color in prod.product_color_set.all %}
                                        {% if color.id == 4 %}
                                        <script>document.getElementById('color').hidden = true; </script>
                                            {% endif %}
                                            <option value="{{ color.id }}">{{ color.color }}</option>
                                        {% endfor %}
                                    </select> 
                                </li>
                            {% endif %}
                            {% if prod.stock == 'Out Of Stock' %}
                            <span>Stock : </span><span style="color: red;">Out Of stock</span>
                            {% endif %}
                        </ul> 
                    </div>
                    
                    {% comment %} {% for i in product %} {% endcomment %}
                    <div class="pro-details-quality">
                        
                        <div class="pro-details-cart">
                            {% if prod.stock == 'Out Of Stock' %}
                            <!-- Product is out of stock -->
                            <input type="submit" value="Add to cart" class="btn" name="submit" disabled>
                            {% elif prod.stock == "In Stock" %}
                            <input type="submit" value="Add to cart" name="submit" class="btn">
                            {% endif %}

                            {% comment %} <a href = "{% url 'cart_add' id=prod.id %}"> <button class="add-cart"> Add To
                                Cart</button></a> {% endcomment %}
                        </div>
                        <div class="pro-details-compare-wishlist pro-details-wishlist " style= "margin-left : 10%;margin-top :1.8%">
                            <a href="{% url 'add_to_wishlist' prod.id %}"><i class="pe-7s-like"></i></a>
                        </div>
                        
                    </div>
                </form>
                    {% comment %} {% endfor %} {% endcomment %}
                </div>
                <!-- product details description area start -->
                <div class="description-review-wrapper">
                    <div class="description-review-topbar nav">
                        <button data-bs-toggle="tab" data-bs-target="#des-details2">Information</button>
                        <button class="active" data-bs-toggle="tab" data-bs-target="#des-details1">Description</button>
                        <a href="{% url 'shop' %}"><button  data-bs-target="#des-details3">Shop More</button></a>
                    </div>
                    <div class="tab-content description-review-bottom">
                        <div id="des-details2" class="tab-pane">
                            <div class="product-anotherinfo-wrapper text-start">
                                <ul>
                                    <li>{{prod.information | safe }}</li>
                                    
                                </ul>
                            </div>
                        </div>
                        <div id="des-details1" class="tab-pane active">
                            <div class="product-description-wrapper">
                                <p>{{prod.description | safe }}</p>
                            </div>
                        </div>
                        
                    </div>
                </div>
                <!-- product details description area end -->
               
            </div>
        </div>
    </div>
    
</div>



{% endblock %}

templates/main/search.html
{% extends "main/header_footer.html" %}

{% block content %}

<div class="shop-category-area pt-100px pb-100px">
    <div class="container">
        <div class="row">

            {% for products in search_product %}

                <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-xs-6 mb-30px">
                                            <!-- Single Prodect -->
                    <div class="product">
                        <span class="badges">
                            <span class="new">{{products.condition}}</span>
                        </span>
                        <div class="thumb">
                            <a href="/product/{{products.id}}" class="image">
                                <img src="/{{products.image}}" alt="Product" height=290 />
                                <img class="hover-image" src="/{{products.image}}" alt="Product" />
                            </a>
                        </div>
                        <div class="content">
                            <span class="category"><a href="#">{{products.categories}}</a></span>
                            <h5 class="title">
                                <a href="single-product.html">{{products.name | truncatewords:3}}</a>
                            </h5>
                            <span class="price">
                                <span class="new">Rs.{{products.price}}/-</span>
                            </span>
                        </div>
                    </div>
                </div>
                                            
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/main/service.html
{% extends "main/header_footer.html" %}

{% block content %}

{% load static %}

<style>

    img {
        height: 20%;
        width: 20%;
        margin-left: 5%;
        margin-bottom: 5%;
        border-radius: 50%; /* Apply circular border */
        object-fit: cover; /* Ensure the image fills the circle */
    }
</style>

<div class="breadcrumb-area" data-bg-image="{% static 'assets/images/shopping.gif' %}">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-12 text-center">
                <h2 class="breadcrumb-title">Services</h2>
                <!-- breadcrumb-list start -->
                <ul class="breadcrumb-list">
                    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                    <li class="breadcrumb-item active">Services</li>
                </ul>
                <!-- breadcrumb-list end -->
            </div>
        </div>
    </div>
</div>
 <!-- service area start -->
<div style="height:auto;width:70%;margin-left:15%">

<p>
    <center>
        At StreeBoutique, we're dedicated to providing exceptional service that celebrates your unique style and ensures you feel confident and comfortable every step of the way.
    </center>
</p>
</div><br><br><br>
 <div style="display: flex; justify-content: center;">
    <img src="{% static 'assets/images/7.png' %}">
    <img src="{% static 'assets/images/8.png' %}">
    <img src="{% static 'assets/images/9.png' %}">
</div>
<div style="display: flex; justify-content: center;">
    <img src="{% static 'assets/images/10.png' %}">
    <img src="{% static 'assets/images/11.png' %}">
</div>

  <!-- service area end -->

{% endblock %}